import { Router } from "express";
import testRoutes from "./test.routes";
import categoryRoutes from "./category.routes";
import colorRoutes from "./color.routes";
import fileTypeRoutes from "./file-type.routes";
import uploadRoutes from "./upload.routes";
import userRoutes from "./user.routes";
import stockRoutes from "./stock.routes";
import collectionRoutes from "./collection.routes";
import planRoutes from "./plan.routes";
import downloadRoutes from "./download.routes";
import transactionRoutes from "./transaction.routes";
import profileRoutes from "./profile.routes";
import userStocksRoutes from "./user-stock.routes";
import dashboardRoutes from "./dashboard.routes";
import notificationRoutes from "./notification.routes";
import topUpRoutes from "./topup.routes";
import webhooksRoutes from "./webhooks.routes";
import subscribeRoutes from "./subscribe.routes";
import donateRoutes from "./donate.routes";
import purchaseStockRoutes from "./purchase-stock.route";
import sessionRoutes from "./session.routes";
import analyticsRoutes from "./admin-access/analytics.routes";
import manageCategoriesRoutes from "./admin-access/manage-categories.routes";
import manageFiletypesRoutes from "./admin-access/manage-filetypes.routes";
import manageVectyzenRoutes from "./admin-access/manage-vectyzen.routes";
import manageStocksRoutes from "./admin-access/manage-stock.routes";

const router = Router();

router.use("/sessions", sessionRoutes);
router.use("/categories", categoryRoutes);
router.use("/colors", colorRoutes);
router.use("/file-types", fileTypeRoutes);
router.use("/uploads", uploadRoutes);
router.use("/stocks", stockRoutes);
router.use("/users", userRoutes);
router.use("/user-stocks", userStocksRoutes);
router.use("/profile", profileRoutes);
router.use("/collections", collectionRoutes);
router.use("/plans", planRoutes);
router.use("/downloads", downloadRoutes);
router.use("/transactions", transactionRoutes);
router.use("/transactions/topup", topUpRoutes);
router.use("/transactions/subscribe", subscribeRoutes);
router.use("/transactions/donate", donateRoutes);
router.use("/transactions/purchase-stock", purchaseStockRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/notifications", notificationRoutes);
router.use("/webhooks", webhooksRoutes);
router.use("/test", testRoutes);

router.use("/admin/analytics", analyticsRoutes);
router.use("/admin/manage-categories", manageCategoriesRoutes);
router.use("/admin/manage-filetypes", manageFiletypesRoutes);
router.use("/admin/manage-vectyzen", manageVectyzenRoutes);
router.use("/admin/manage-stocks", manageStocksRoutes);

export default router;
