import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/provider/react-query-provider";
import Script from "next/script";

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Vectyz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          strategy="afterInteractive"
          type="text/javascript"
          src="//e.crmrkt.com/product_embed.js"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`${montserrat.className} antialiased`}>
        <ReactQueryProvider>{children}</ReactQueryProvider>

        <Toaster richColors position="top-center" theme="dark" />
      </body>
    </html>
  );
}
